blank_issues_enabled: false
contact_links:
  - name: SDK Integration Support
    url: https://developer.flutterwave.com/
    about: If you're having general trouble with your integration, Kindly contact our support team.
