name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  Unit tests and coverage scans:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run unit tests and coverage scan
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        RAVE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pip install coverage
        coverage run test.py

    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v2
