name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  code-check:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run unit tests and coverage scan
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        RAVE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pip install coverage
        coverage run test.py

    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v2

    - name: push build status as webhook to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
